pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://developer.dji.com/maven2" }
        maven { url "https://api.xnpe.com/maven" }   // legacy fallback
        maven { url "https://jitpack.io" }
    }
}

rootProject.name = "SClassFencingApp"
include ':app'
