apply plugin: 'com.android.application'

android {
    namespace 'io.github.dunkaroo173.uflfencing'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.dunkaroo173.uflfencing'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
